import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { ClassifiedDiffFile } from './classify-diff.ts';
import type { MissingMarker } from './apply-runner.ts';

export interface ManualEditFileInput {
  csId: string;
  classified: ClassifiedDiffFile;
  viewerUrl?: string;
  missingMarkers: readonly MissingMarker[];
}

export function manualEditFilePath(repoRoot: string, csId: string): string {
  return resolve(repoRoot, '.automation/manual-edits', `${csId}.md`);
}

export function writeManualEditFile(repoRoot: string, input: ManualEditFileInput): string {
  const path = manualEditFilePath(repoRoot, input.csId);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, buildManualEditMarkdown(input), 'utf-8');
  return path;
}

export function buildManualEditMarkdown(input: ManualEditFileInput): string {
  const reportOnly = input.classified.changes.filter(c => c.decision === 'report-only');
  const codePaths = Array.from(
    new Set(reportOnly.map(c => c.target?.code).filter((c): c is string => Boolean(c)))
  ).sort();

  const lines: string[] = [
    `# ${input.csId} — Manual edit needed`,
    '',
    `Designer approved this change set, but no marker is mapped for any of the ${reportOnly.length} change(s). Edit the source files below manually to apply the design changes; then push to this PR branch and merge.`,
    '',
  ];

  if (input.viewerUrl) {
    lines.push(`Before/after viewer: ${input.viewerUrl}`, '');
  }

  if (codePaths.length > 0) {
    lines.push('## Code paths to edit', '');
    for (const path of codePaths) {
      lines.push(`- \`${path}\``);
    }
    lines.push('');
  } else {
    lines.push('## Code paths to edit', '', '_No mapped code paths in the classified diff._', '');
  }

  if (input.missingMarkers.length > 0) {
    lines.push('## Missing markers', '');
    for (const m of input.missingMarkers) {
      lines.push(`- \`${m.code}\` (${m.kind}): ${m.nodeIds.join(', ')}`);
    }
    lines.push('');
  }

  lines.push('## Change summary', '');
  lines.push('| key | classes | nodeName |');
  lines.push('|---|---|---|');
  for (const c of reportOnly) {
    lines.push(`| \`${c.key}\` | ${c.classes.join(', ')} | ${c.nodeName} |`);
  }
  lines.push('');

  lines.push('---', '', '_This file was generated by `designer-approval.ts` because the marker-based auto-edit found no applicable markers._');

  return lines.join('\n');
}
